// <auto-generated />
using System;
using Ecomerce_Back_End.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112170945_ImgUrlCategories")]
    partial class ImgUrlCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("BackEnd.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackEnd.Models.Case", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriveBays")
                        .HasColumnType("int");

                    b.Property<string>("FormFactorSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasGlassPanel")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCoolerHeightMM")
                        .HasColumnType("int");

                    b.Property<int>("MaxGpuLengthMM")
                        .HasColumnType("int");

                    b.Property<string>("PsuFormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rgb")
                        .HasColumnType("bit");

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.CpuCooler", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<int>("FanSize")
                        .HasColumnType("int");

                    b.Property<int>("Fancount")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("MaxRpm")
                        .HasColumnType("int");

                    b.Property<int>("NoiseLevel")
                        .HasColumnType("int");

                    b.Property<bool>("Rgb")
                        .HasColumnType("bit");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CpuCoolers", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.GraphicsCard", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lenght")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCIeVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.Property<int>("VRam")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.ToTable("Graficas", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.Motherboard", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasWiFi")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRamGB")
                        .HasColumnType("int");

                    b.Property<int>("RamSlots")
                        .HasColumnType("int");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedMemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Motherboards", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.PowerSupply", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<string>("Certidication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Modular")
                        .HasColumnType("bit");

                    b.Property<bool>("Rgb")
                        .HasColumnType("bit");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.ToTable("PowerSupplies", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.Processors", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("BaseClockGHz")
                        .HasColumnType("real");

                    b.Property<float>("BoostClockGHz")
                        .HasColumnType("real");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("bit");

                    b.Property<string>("Lithography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.ToTable("Processors", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.Ram", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<string>("MemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rgb")
                        .HasColumnType("bit");

                    b.Property<int>("SpeedMTs")
                        .HasColumnType("int");

                    b.ToTable("Rams", (string)null);
                });

            modelBuilder.Entity("BackEnd.Models.Storage", b =>
                {
                    b.HasBaseType("Product");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadSpeedMBps")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<int>("WriteSpeedMBps")
                        .HasColumnType("int");

                    b.ToTable("Storages", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("BackEnd.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("BackEnd.Models.Case", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.Case", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.CpuCooler", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.CpuCooler", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.GraphicsCard", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.GraphicsCard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Motherboard", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.Motherboard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.PowerSupply", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.PowerSupply", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Processors", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.Processors", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Ram", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.Ram", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Storage", b =>
                {
                    b.HasOne("Product", null)
                        .WithOne()
                        .HasForeignKey("BackEnd.Models.Storage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
